### ISSUE TITLE
bun publish to GitHub Package Registry fails with 400 Bad Request / no attachments present in packument

### ISSUE THREAD

**Issue by Korni22** [oven-sh/setup-bun#110]
Hey everyone!

I am trying to use `bun publish` to publish a package into the GitHub Package Registry using GitHub Actions.

The job has all the permissions it takes:
```
permissions:
  contents: read
  id-token: write # This is required for requesting the JWT
  packages: write
```

I setup bun like this:
```
- name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@our-org'
```

Install the dependencies:
```
- name: Install dependencies
        run: bun install --frozen-lockfile
```

Build the project:
```
      - name: Build project
        run: bun run build
```

And try to publish:
```
      - name: Publish package
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bun publish --verbose
```

which errors with:
```
Unpacked size: 0.79MB
Packed size: 0.75MB
400 Bad Request: https://npm.pkg.github.com/@our-org%2fpackage-name
 - no attachments present in packument
Tag: latest
Access: default
Registry: https://npm.pkg.github.com/
```

Maybe the package.json is the root cause?
```
{
  "name": "@our-org/package-name",
  "repository": "our-org/package-name",
}
```

However, it does work using yarn (classic).

The `%2f` confuses me, maybe its related to [#14592](https://github.com/oven-sh/bun/issues/14592)?
