### ISSUE TITLE
bun-version-file should be able to read from engines for package.json

### ISSUE THREAD

**Issue by jbojcic1** [oven-sh/setup-bun#115]
Currently if you use:
```
    - name: Install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: package.json
```

it tries to read the version from the `packageManager` property. It should be possible to also read it from the [engines](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines)
