### ISSUE TITLE
Incorrect bun version: 0.5.6

### ISSUE THREAD

**Issue by vkzrx** [oven-sh/setup-bun#19]
Hello,

The wrong bun version is downloaded whether the version is specified or not.
It was working fine until very recently (~1h)
I'm always getting `v0.5.6` which seems broken for workspaces

I'm using a minimal config

```yml
name: CI

on:
  pull_request:
  push:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0

      - name: Install Dependencies
        run: bun install

      - name: Run
        run: bun run index.ts
```

I have a minimal repo here: https://github.com/0xYami/bun-repro-ci-bun-version

Log without version specified (should defaults to `latest`): https://github.com/0xYami/bun-repro-ci-bun-version/actions/runs/6151432253/job/16691465674#step:3:30

Log with version specified (should be `1.0.0`): https://github.com/0xYami/bun-repro-ci-bun-version/actions/runs/6151502117/job/16691677799#step:3:31
