### ISSUE TITLE
Custom registry-url and scope not working

### ISSUE THREAD

**Issue by JakobLierman** [oven-sh/setup-bun#33]
I have the following step:
```yaml
- name: Use Bun v1
  uses: oven-sh/setup-bun@v1
  with:
    registry-url: "https://npm.pkg.github.com"
    scope: "@companyName"
```

In the logs, I get this warning: `Unexpected input(s) 'registry-url', 'scope', valid inputs are ['bun-version']`.

There are [setup instructions](https://github.com/oven-sh/setup-bun?tab=readme-ov-file#setup-custom-registry-url-and-scope-for-private-packages) available in the README.md file, but this doesn't seem to reflect what's actually deployed. I can also see some work being done in the commit logs, seems like some runners are throwing an error.

**Comment by JakobLierman** [comment]
Looks like it's just a warning that hasn't been removed.

Whilst installing my dependencies, it uses the correct registry. It however throws a 401 error, even though the `BUN_AUTH_TOKEN` is being set correctly.

```yaml
- name: Install dependencies
  env:
    BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: bun install --frozen-lockfile
```

Error on the install step: `GET https://npm.pkg.github.com/download/@companyName/eslint-config/1.0.0/[...] - 401`

**Comment by praveenpuglia** [comment]
I did the same but I get the following error
```
error: FailedToOpenSocket downloading tarball @myorg/my-package@0.7.0
```

for all the `@myorg` scoped packages. Would GITHUB_TOKEN not work and I have to create a separate token for this?

**Comment by vitoorgomes** [comment]
> Looks like it's just a warning that hasn't been removed.
> 
> Whilst installing my dependencies, it uses the correct registry. It however throws a 401 error, even though the `BUN_AUTH_TOKEN` is being set correctly.
> 
> ```yaml
> - name: Install dependencies
>   env:
>     BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>   run: bun install --frozen-lockfile
> ```
> 
> Error on the install step: `GET https://npm.pkg.github.com/download/@companyName/eslint-config/1.0.0/[...] - 401`

howdy 👋🏼  I was the one that implemented this feature, but for what I'm seeing, when it was merged, it didn't create a new release, so using `oven-sh/setup-bun@v1` is still using the outdated version

when it's working, the warning should be removed, as well as showing as a log on job step (line 10) this screenshot is from my private testing before merging #16 

<img width="747" alt="image" src="https://github.com/oven-sh/setup-bun/assets/41302394/06a25634-0a93-425c-a969-dfde34211b76">

@xHyroM @Electroid would be possible to manually generate a new release version with source code from main branch?

**Comment by vitoorgomes** [comment]
> I did the same but I get the following error
> 
> ```
> error: FailedToOpenSocket downloading tarball @myorg/my-package@0.7.0
> ```
> 
> for all the `@myorg` scoped packages. Would GITHUB_TOKEN not work and I have to create a separate token for this?

aside from the previous comment about the action problem, you need to make sure that your token has access to private packages/repos, when this action get a new release you will be able to test it properly

**Comment by praveenpuglia** [comment]
@vitoorgomes hey! I have made sure the token has access! Waiting for the release! 🙌

**Comment by vitoorgomes** [comment]
hey guys @praveenpuglia @JakobLierman I totally forgot that you can use github actions versions in different ways

tags are the best option for control over things, but you can also use any branch name or even a commit sha

although you don't have a good control when using the branch name, you can do it, so you guys don't have to wait the release version, the step would be something like this

```
      - uses: oven-sh/setup-bun@main # or @commit_sha
        with:
          bun-version: latest
          registry-url: 'https://npm.pkg.github.com'  # or any registry url that you guys have
          scope: '@foo-bar'
```

hope this helps 😄 

ps: I think it's still good to keep this issue so the version using tags would be published and we stop using `@main`
