### ISSUE TITLE
Custom registry timeout

### ISSUE THREAD

**Issue by kevinpoot** [oven-sh/setup-bun#43]
After following the docs and reading through [this issue](https://github.com/oven-sh/setup-bun/issues/33) i can't get the Github actions to work with using a custom registry.

The config looks like this:
```yaml
steps:
      - uses: actions/checkout@v3
      - name: Use Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: latest
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@company'
```

The install seems to timeout with the message: `The job running on runner GitHub Actions 5 has exceeded the maximum execution time of 360 minutes.`. It seems my config should work since it's following the docs.

Any ideas?
