### ISSUE TITLE
Does this work without Node.js?

### ISSUE THREAD

**Issue by PaulRBerg** [oven-sh/setup-bun#46]
Can I use this GitHub Action without previously installing Node.js? E.g.

```yaml
jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: "lts/*"

      - name: "Install Bun"
        uses: "oven-sh/setup-bun@v1"
```

Is the first step necessary?

Side note - would you like to enable [Discussions](https://github.com/features/discussions) in this repository? I would have opened a discussion instead of an issue.
