### ISSUE TITLE
Bun setup fails when other bun apps are running on the background.

### ISSUE THREAD

**Issue by Kochiyama** [oven-sh/setup-bun#49]
I've set up the ci/cd using Github actions as following:

```yml
name: Deploy on Test Server
run-name: ${{ github.actor }} is deploying to test server

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: test

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Create env file
        run: cp ../.env .env.local

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Generate Build
        run: bun run build

      - name: Restart process
        run: pm2 restart myapp
```

But, when the setup-bun action can't setup bun without stopping every other process running bun, ci error:

```
Run oven-sh/setup-bun@v1
  with:
    bun-version: latest
Downloading a new version of Bun: https://bun.sh/download/latest/linux/x64?avx[2](https://github.com/whatstalk/whatstalk-web/actions/runs/7533224581/job/20505337934#step:5:2)=true&profile=false
/usr/bin/unzip -o -q /usr/apps/_temp/bd9fb8b4-08[3](https://github.com/whatstalk/whatstalk-web/actions/runs/7533224581/job/20505337934#step:5:3)e-[4](https://github.com/whatstalk/whatstalk-web/actions/runs/7533224581/job/20505337934#step:5:5)7f[5](https://github.com/whatstalk/whatstalk-web/actions/runs/7533224581/job/20505337934#step:5:6)-9e[6](https://github.com/whatstalk/whatstalk-web/actions/runs/7533224581/job/20505337934#step:5:7)d-0c4d8cc2430a
Error: Error: ETXTBSY: text file is busy, copyfile '/usr/apps/_temp/3625e59f-8c63-4659-90a9-ede291cca2fc/bun-linux-x64-baseline/bun' -> '/home/marcelokochiyama/.bun/bin/bun'
```

It is an expected behaviour or it should work even with other apps running with bun on the background?
