### ISSUE TITLE
action's v1 tag not getting updated

### ISSUE THREAD

**Issue by panva** [oven-sh/setup-bun#50]
The [v1 tag](https://github.com/oven-sh/setup-bun/releases/tag/v1) is not getting updated with new v1.x releases and is therefore stuck on version of `setup-bun` from February 2023.

As a result the readme's own usage example does not take benefit of the fixes and recent releases.

### **Use v1.1.1 for now**
_edited by xHyroM_

**Comment by Electroid** [comment]
Thanks for flagging this, will fix.

**Comment by jcbhmr** [comment]
For auto-updating vN tags, check out https://github.com/actions/publish-action. It's used like:

```yml
name: Release new action version

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}

jobs:
  update_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ env.TAG_NAME }}
```

then it will automagically update the vN tag whenever a new release is published

**Comment by lexabu** [comment]
Will this issues PR resolve this error on GitHub actions? 

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: oven-sh/setup-bun@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I am using this setup command in my yml:

```
 name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
```
