### ISSUE TITLE
Freezes on first run on self-hosted

### ISSUE THREAD

**Issue by deadlinecode** [oven-sh/setup-bun#65]
If you setup a new github project and add a self hosted runner and try to use the task it gets stuck after this:
```sh
Downloading a new version of Bun: https://bun.sh/download/1.0.26/linux/x64?avx2=true&profile=false
/usr/bin/unzip -o -q /home/XXX/GHAction/_temp/6c34e31[5](https://github.com/XXX/GHAction/actions/runs/8131459921/job/22220810867#step:3:6)-e774-4d10-b078-4022[6](https://github.com/XXX/GHAction/actions/runs/8131459921/job/22220810867#step:3:7)191e70c
/home/XXX/.bun/bin/bun --revision
1.0.26+c[7](https://github.com/XXX/GHAction/actions/runs/8131459921/job/22220810867#step:3:8)5e76[8](https://github.com/XXX/GHAction/actions/runs/8131459921/job/22220810867#step:3:9)a6
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/XXX/GHAction/projects/RSAS/rsas/rsas --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~31 MB (32664145 B)
Cache saved successfully
```

After this it just does nothing
It only works if you then cancel the run and start a new one
My workflow is also pretty simple
```yml
name: Build Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.26
      - name: Build
        run: bun run build
```
The runner is running on Ubuntu 22.04.3 LTS
Here is my neofetch:
```
            .-/+oossssoo+/-.               XXX@homelabs1
        `:+ssssssssssssssssss+:`           -------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.3 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: PowerEdge R710
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.15.0-94-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 20 days, 20 hours, 58 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 902 (dpkg), 5 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1024x768
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/0
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon E5620 (16) @ 2.393GHz
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: 08:03.0 Matrox Electronics Systems Ltd. MGA G200eW WPCM450
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 1218MiB / 64381MiB
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```
