### ISSUE TITLE
Setup Bun Action Fails Due to Request Timeout

### ISSUE THREAD

**Issue by azishio** [oven-sh/setup-bun#82]
# Workaround

(Edited by @Jarred-Sumner)

```yaml
      - name: Setup Bun
        uses: oven-sh/setup-bun@1.2.2
        with:
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-${{runner.os == 'macOS' && 'darwin' || runner.os}}-${{ runner.arch == 'X64' && 'x64' || 'arm64' }}.zip"
```

The `bun-download-url` input lets you override the download URL to use and skip the redirect / version resolution. 

-----

# Description
I'm using `oven-sh/setup-bun@v1` in my GitHub Actions workflow to deploy a Next.js site to GitHub Pages. This action used to work without issues, but today I encountered repeated request timeouts when trying to download Bun.

# Console Output
Here is the relevant part of the console output:

```
Run oven-sh/setup-bun@v1
  with:
    bun-version: latest
    no-cache: false
Downloading a new version of Bun: https://bun.sh/download/latest/linux/x64?avx2=true&profile=false
Request timeout: /download/latest/linux/x64?avx2=true&profile=false
Waiting 18 seconds before trying again
Request timeout: /download/latest/linux/x64?avx2=true&profile=false
Waiting 20 seconds before trying again
```

# [Workflow File](https://github.com/azishio/seismic-response-web/blob/daaac22da233fe2b452c919e6bb7d159f8a98bfc/.github/workflows/nextjs.yml)
Below is the workflow file I'm using:

```yaml
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - name: Install dependencies
        run: bun install
      - name: Build with Next.js
        run: bun run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

(This text has been translated from Japanese by ChatGPT and DeepL)

**Comment by nephix** [comment]
Same here

**Comment by Jarred-Sumner** [comment]
Looking into this now.

**Comment by hmmhmmhm** [comment]
<img width="786" alt="스크린샷 2024-06-02 오후 7 09 36" src="https://github.com/oven-sh/setup-bun/assets/38493722/1705cad9-c558-473e-9b88-45c650d1d799">

I'm getting the same error. I've posted the above issue on Bun's official discord.
https://discord.com/channels/876711213126520882/1246770196992229428

**Comment by Jarred-Sumner** [comment]
It seems that [Fly.io is having an incident](https://status.flyio.net/) in their Bucharest region, which is also where this redirecting app is currently hosted. Looking into migrating to a different region.

**Workaround to try**: 
```yaml
      - name: Setup Bun
        uses: oven-sh/setup-bun@1
        with:
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-${{runner.os == 'macOS' && 'darwin' || runner.os}}-${{ runner.arch == 'X64' && 'x64' || 'arm64' }}.zip"
```

The `bun-download-url` input lets you override the download URL to use and skip the redirect / version resolution.

**Comment by hmmhmmhm** [comment]
<img width="550" alt="스크린샷 2024-06-02 오후 7 38 04" src="https://github.com/oven-sh/setup-bun/assets/38493722/52f5c04c-1642-4624-a7bb-99ab569d8016">
<img width="525" alt="스크린샷 2024-06-02 오후 7 39 03" src="https://github.com/oven-sh/setup-bun/assets/38493722/bb52022d-cf6d-4c7d-ada8-912f349fe882">
<img width="750" alt="스크린샷 2024-06-02 오후 7 39 45" src="https://github.com/oven-sh/setup-bun/assets/38493722/7cfb7ccd-6645-4a88-b466-5a114d97d8c1">

@Jarred-Sumner The alternative you provided doesn't seem to be working yet.

**Comment by Jarred-Sumner** [comment]
Looks like `bun-download-url` is not included in actions.yml, I will push an update. 

https://github.com/oven-sh/setup-bun/blob/8f24390df009a496891208e5e36b8a1de1f45135/src/index.ts#L65

**Comment by azishio** [comment]
Warnings occurred, but @Jarred-Sumner 's measures enabled him to deploy the system successfully.

Setup Bun
```
Warning: Unexpected input(s) 'bun-download-url', valid inputs are ['bun-version', 'registry-url', 'scope', 'no-cache']
Run oven-sh/setup-bun@v1
  with:
    bun-version: latest
    bun-download-url: https://github.com/oven-sh/bun/releases/latest/download/bun-Linux-x64.zip
    no-cache: false
Downloading a new version of Bun: https://github.com/oven-sh/bun/releases/latest/download/bun-Linux-x64.zip
/usr/bin/unzip -o -q /home/runner/work/_temp/4ec6c1ca-ad97-44f5-8f04-7df9db8903dc
/home/runner/.bun/bin/bun --revision
1.1.1[2](https://github.com/azishio/seismic-response-web/actions/runs/9337673936/job/25699852379#step:3:2)+43f0913c3
```

Post Setup Bun
```
Warning: Unexpected input(s) 'bun-download-url', valid inputs are ['bun-version', 'registry-url', 'scope', 'no-cache']
Post job cleanup.
```

https://github.com/azishio/seismic-response-web/actions/runs/9337673936


(By the way, the inclusion of my project's commits in this history was an unintended behaviour.
Next time I'll look into how not to do that and run the commits.)

**Comment by hmmhmmhm** [comment]
> Warnings occurred, but @Jarred-Sumner 's measures enabled him to deploy the system successfully.
> 
> https://github.com/azishio/seismic-response-web/actions/runs/9337673936

<img width="517" alt="스크린샷 2024-06-02 오후 7 55 18" src="https://github.com/oven-sh/setup-bun/assets/38493722/0ca9624f-7050-45a5-9ff7-04f852231841">

Thx bro! this is work!
```
- name: Setup Bun
  uses: oven-sh/setup-bun@v1
  with:
    bun-version: latest
    bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-${{runner.os == 'macOS' && 'darwin' || runner.os}}-${{ runner.arch == 'X64' && 'x64' || 'arm64' }}.zip"
```
