### ISSUE TITLE
Should `bunx` be available after this action?

### ISSUE THREAD

**Issue by jakeboone02** [oven-sh/setup-bun#9]
Hi, I'm using this action to set up Bun in a CI job, and I expected `bunx` to be available for subsequent steps after this:

```yaml
  - name: Setup Bun
    uses: oven-sh/setup-bun@v1
    with:
      bun-version: latest
```

Instead I get `bunx: command not found`. Is the intention to make `bunx` available, and if not, is there a workaround?
