### ISSUE TITLE
Installs `canary` instead of `latest`

### ISSUE THREAD

**Issue by RobinTail** [oven-sh/setup-bun#97]
Even when `latest` is requested explicitly.
The dist-tag `latest` should mean "latest stable".

### The step in workflow

```yaml
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
```

### The output

```
Run oven-sh/setup-bun@v2
  with:
    bun-version: latest
    no-cache: false
Downloading a new version of Bun: https://bun.sh/download/latest/linux/x64?avx2=true&profile=false
/usr/bin/unzip -o -q /home/runner/work/_temp/9ffd85c1-a389-491d-adab-e5f6f7615d49.zip
/home/runner/.bun/bin/bun --revision
1.1.22-canary.96+df33f2b2a
```

### Screenshot

![image](https://github.com/user-attachments/assets/0ddfff84-97c8-44e3-85e8-8cc06f6f1022)
